stages:
  - tests

parser_test:
  image: python:3.7-slim

  stage: tests

  before_script:
    - pip install -r requirements.txt

  script:
    - cd parser
    - mkdir -p dump-html
    - pytest .

to_typescript_test:
  image: python:3.7-slim

  stage: tests

  before_script:
    - pip install -r requirements.txt

  script:
    - mkdir -p dump-html
    - cd to_typescript
    - pytest .
