stages:
  - tests

test:
  image: python:3.7-slim

  stage: tests

  before_script:
    - pip install -r requirements.txt

  script:
    - mkdir -p dump-html
    - echo $PYTHONPATH
    - export PYTHONPATH=$PWD
    - pytest .
